services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JENKINS_OPTS: "--argumentsRealm.passwd.${JENKINS_USER}=${JENKINS_PASS} --argumentsRealm.roles.${JENKINS_USER}=admin"
    volumes:  
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_GIT_DIR}:${HOST_GIT_DIR}
      - ${HOST_BACKUP_DIR}:${HOST_BACKUP_DIR}